import { DevicePackageType } from "./devices";


export enum PinType{

    //GENERAL PINS
    'IN' = 'IN',   
    'OUT' = 'OUT',
    'INOUT' = 'INOUT',
    'GND' = 'GND',
    'VCC' = 'VCC',
    //CHIP CUSTOM PINS
    'CLR' = 'CLR',
    'CLK' = 'CLK',
    'PD' = 'PD',
    'OE' = 'OE',
    //JTAG
    'TDI' = 'TDI',
    'TMS' = 'TMS',
    'TCK' = 'TCK',
    'TDO' = 'TDO',
    //NOT CONNECTED
    'NC' = 'NC'

}

export interface Pin{
    pin: number;
    pinType: PinType[];
}
export interface PinConfiguration{
    name: string;
    deviceType: DevicePackageType;
    pinCount: number;
    pins: Pin[];
    

}


export const pinConfigurations = [
    {
        name: '16v8',
        deviceType: DevicePackageType.dip,
        pinCount: 20,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.IN, PinType.OE] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '16v8',
        deviceType: DevicePackageType.plcc,
        pinCount: 20,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.IN, PinType.OE] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '20v8',
        pinCount: 24,
        deviceType: DevicePackageType.dip,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.GND] },
            { pin:13, pinType: [PinType.IN, PinType.OE] },
            { pin:14, pinType: [PinType.IN] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.IN] },
            { pin:24, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '20v8powerdown',
        deviceType: DevicePackageType.dip,
        pinCount: 24,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN, PinType.PD] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.GND] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '20v8',
        deviceType: DevicePackageType.plcc,
        pinCount: 28,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.IN, PinType.CLK] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.NC] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.IN] },
            { pin:13, pinType: [PinType.IN] },
            { pin:14, pinType: [PinType.GND] },
            { pin:15, pinType: [PinType.NC] },
            { pin:16, pinType: [PinType.IN, PinType.OE] },
            { pin:17, pinType: [PinType.IN] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.NC] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.IN] },
            { pin:28, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '20v8powerdown',
        deviceType: DevicePackageType.plcc,
        pinCount: 28,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.IN, PinType.CLK] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN, PinType.PD] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.NC] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.IN] },
            { pin:13, pinType: [PinType.IN] },
            { pin:14, pinType: [PinType.GND] },
            { pin:15, pinType: [PinType.NC] },
            { pin:16, pinType: [PinType.IN] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.NC] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '22v10',
        deviceType: DevicePackageType.dip,
        pinCount: 24,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.GND] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: '22v10',
        deviceType: DevicePackageType.plcc,
        pinCount: 28,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.IN, PinType.CLK] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.NC] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.IN] },
            { pin:13, pinType: [PinType.IN] },
            { pin:14, pinType: [PinType.GND] },
            { pin:15, pinType: [PinType.NC] },
            { pin:16, pinType: [PinType.IN] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.NC] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: 'v750',
        deviceType: DevicePackageType.dip,
        pinCount: 24,
        pins:[
            { pin:1, pinType: [PinType.IN] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.IN] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.GND] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: 'v750c',
        deviceType: DevicePackageType.plcc,
        pinCount: 28,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.IN] },
            { pin:5, pinType: [PinType.IN] },
            { pin:6, pinType: [PinType.IN] },
            { pin:7, pinType: [PinType.IN] },
            { pin:8, pinType: [PinType.NC] },
            { pin:9, pinType: [PinType.IN] },
            { pin:10, pinType: [PinType.IN] },
            { pin:11, pinType: [PinType.IN] },
            { pin:12, pinType: [PinType.IN] },
            { pin:13, pinType: [PinType.IN] },
            { pin:14, pinType: [PinType.GND] },
            { pin:15, pinType: [PinType.NC] },
            { pin:16, pinType: [PinType.IN] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.NC] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.VCC] }
        ] as Pin[]
    },
    {
        name: 'v2500',
        deviceType: DevicePackageType.dip,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.VCC] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.IN] },
            { pin:18, pinType: [PinType.IN] },
            { pin:19, pinType: [PinType.IN] },
            { pin:20, pinType: [PinType.IN] },
            { pin:21, pinType: [PinType.IN] },
            { pin:22, pinType: [PinType.IN] },
            { pin:23, pinType: [PinType.IN] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.GND] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.IN] },
            { pin:38, pinType: [PinType.IN] },
            { pin:39, pinType: [PinType.IN] },
            { pin:40, pinType: [PinType.IN] }
        ] as Pin[]
    },
    {
        name: 'v2500',
        deviceType: DevicePackageType.plcc,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLK] },
            { pin:2, pinType: [PinType.IN] },
            { pin:3, pinType: [PinType.IN] },
            { pin:4, pinType: [PinType.GND] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.VCC] },
            { pin:12, pinType: [PinType.VCC] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.IN] },
            { pin:20, pinType: [PinType.IN] },
            { pin:21, pinType: [PinType.IN] },
            { pin:22, pinType: [PinType.IN] },
            { pin:23, pinType: [PinType.IN] },
            { pin:24, pinType: [PinType.IN] },
            { pin:25, pinType: [PinType.IN] },
            { pin:26, pinType: [PinType.GND] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.GND] },
            { pin:34, pinType: [PinType.GND] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.IN] },
            { pin:42, pinType: [PinType.IN] },
            { pin:43, pinType: [PinType.IN] },
            { pin:44, pinType: [PinType.IN] }
        ] as Pin[]
    },
    {
        name: 'f1500',
        deviceType: DevicePackageType.plcc,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.IN, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT, PinType.PD] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.VCC] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.GND] },
            { pin:23, pinType: [PinType.VCC] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.GND] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.VCC] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.IN, PinType.CLK] },
            { pin:44, pinType: [PinType.IN, PinType.OE] }
        ] as Pin[]
    },
    {
        name: 'f1500',
        deviceType: DevicePackageType.tqfp,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.IN, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT, PinType.PD] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.VCC] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.GND] },
            { pin:23, pinType: [PinType.VCC] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.GND] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.VCC] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.NC] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.IN, PinType.CLK] },
            { pin:44, pinType: [PinType.IN, PinType.OE] }
        ] as Pin[]
    },
    {
        name: 'f1502',
        deviceType: DevicePackageType.plcc,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.IN, PinType.CLK, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT, PinType.PD] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.INOUT, PinType.PD] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.VCC] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.GND] },
            { pin:23, pinType: [PinType.VCC] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT, PinType.PD] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.GND] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.VCC] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT, PinType.CLK] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.IN, PinType.CLK] },
            { pin:44, pinType: [PinType.IN, PinType.OE] }
        ] as Pin[]
    },
    {
        name: 'f1502',
        deviceType: DevicePackageType.tqfp,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:2, pinType: [PinType.INOUT] },
            { pin:3, pinType: [PinType.INOUT] },
            { pin:4, pinType: [PinType.GND] },
            { pin:5, pinType: [PinType.INOUT, PinType.PD] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.VCC] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.GND] },
            { pin:17, pinType: [PinType.VCC] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT, PinType.PD] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.GND] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.VCC] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.CLK] },
            { pin:36, pinType: [PinType.GND] },
            { pin:37, pinType: [PinType.IN, PinType.CLK] },
            { pin:38, pinType: [PinType.OE] },
            { pin:39, pinType: [PinType.IN, PinType.CLR] },
            { pin:40, pinType: [PinType.CLK, PinType.OE] },
            { pin:41, pinType: [PinType.VCC] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.INOUT] },
            { pin:44, pinType: [PinType.INOUT] }
        ] as Pin[]
    },

    {
        name: 'f1504',
        deviceType: DevicePackageType.plcc,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.IN, PinType.CLK, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT, PinType.PD] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.GND] },
            { pin:11, pinType: [PinType.INOUT, PinType.PD] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.VCC] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.GND] },
            { pin:23, pinType: [PinType.VCC] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT, PinType.PD] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.GND] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.VCC] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT, PinType.CLK] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.IN, PinType.CLK] },
            { pin:44, pinType: [PinType.IN, PinType.OE] }
        ] as Pin[]
    },
    {
        name: 'f1504',
        deviceType: DevicePackageType.tqfp,
        pinCount: 44,
        pins:[
            { pin:1, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:2, pinType: [PinType.INOUT] },
            { pin:3, pinType: [PinType.INOUT] },
            { pin:4, pinType: [PinType.GND] },
            { pin:5, pinType: [PinType.INOUT, PinType.PD] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.VCC] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.GND] },
            { pin:17, pinType: [PinType.VCC] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT, PinType.PD] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.GND] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.VCC] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.NC] },
            { pin:32, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.CLK] },
            { pin:36, pinType: [PinType.GND] },
            { pin:37, pinType: [PinType.IN, PinType.CLK] },
            { pin:38, pinType: [PinType.IN, PinType.OE] },
            { pin:39, pinType: [PinType.IN, PinType.CLR] },
            { pin:40, pinType: [PinType.INOUT, PinType.CLK, PinType.OE] },
            { pin:41, pinType: [PinType.VCC] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.INOUT] },
            { pin:44, pinType: [PinType.INOUT] }
        ] as Pin[]
    },
    {
        name: 'f1504',
        deviceType: DevicePackageType.plcc,
        pinCount: 68,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.CLK, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.GND] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.VCC] },
            { pin:12, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.GND] },
            { pin:17, pinType: [PinType.INOUT, PinType.PD] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.VCC] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.GND] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.VCC] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.GND] },
            { pin:35, pinType: [PinType.VCC] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT, PinType.PD] },
            { pin:38, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.VCC] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.INOUT] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.INOUT] },
            { pin:48, pinType: [PinType.GND] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:51, pinType: [PinType.INOUT] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.VCC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.INOUT] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:58, pinType: [PinType.GND] },
            { pin:59, pinType: [PinType.INOUT] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.INOUT] },
            { pin:62, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:63, pinType: [PinType.VCC] },
            { pin:64, pinType: [PinType.INOUT] },
            { pin:65, pinType: [PinType.IN, PinType.CLK] },
            { pin:66, pinType: [PinType.GND] },
            { pin:67, pinType: [PinType.IN, PinType.CLK] },
            { pin:68, pinType: [PinType.IN, PinType.OE] }          
        ] as Pin[]
    },
    ,
    {
        name: 'f1504',
        deviceType: DevicePackageType.plcc,
        pinCount: 84,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.CLK, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.GND] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.VCC] },
            { pin:14, pinType: [PinType.IN, PinType.TDI] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.GND] },
            { pin:20, pinType: [PinType.IN, PinType.PD] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.NC] },
            { pin:26, pinType: [PinType.VCC] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.GND] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.VCC] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.VCC] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.INOUT] },
            { pin:46, pinType: [PinType.INOUT, PinType.PD] },
            { pin:47, pinType: [PinType.GND] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT] },
            { pin:51, pinType: [PinType.INOUT] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.VCC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.INOUT] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.GND] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.INOUT] },
            { pin:62, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.VCC] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.INOUT] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.INOUT] },
            { pin:71, pinType: [PinType.IN, PinType.TDO] },
            { pin:72, pinType: [PinType.GND] },
            { pin:73, pinType: [PinType.INOUT] }, 
            { pin:74, pinType: [PinType.INOUT] },
            { pin:75, pinType: [PinType.INOUT] },
            { pin:76, pinType: [PinType.INOUT] },
            { pin:77, pinType: [PinType.INOUT] },
            { pin:78, pinType: [PinType.VCC] },
            { pin:79, pinType: [PinType.INOUT] },
            { pin:80, pinType: [PinType.INOUT] },
            { pin:81, pinType: [PinType.IN, PinType.CLK] },
            { pin:82, pinType: [PinType.GND] },
            { pin:83, pinType: [PinType.IN, PinType.CLK] },
            { pin:84, pinType: [PinType.IN, PinType.OE] }        
        ] as Pin[]
    },
    ,
    {
        name: 'f1508',
        deviceType: DevicePackageType.plcc,
        pinCount: 84,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.CLR] },
            { pin:2, pinType: [PinType.IN, PinType.CLK, PinType.OE] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.GND] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT, PinType.PD] },
            { pin:13, pinType: [PinType.VCC] },
            { pin:14, pinType: [PinType.IN, PinType.TDI] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.GND] },
            { pin:20, pinType: [PinType.IN] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.VCC] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.GND] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.VCC] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT] },
            { pin:42, pinType: [PinType.GND] },
            { pin:43, pinType: [PinType.VCC] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.INOUT, PinType.PD] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.GND] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT] },
            { pin:51, pinType: [PinType.INOUT] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.VCC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.INOUT] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.GND] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.INOUT] },
            { pin:62, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.VCC] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.INOUT] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.INOUT] },
            { pin:71, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:72, pinType: [PinType.GND] },
            { pin:73, pinType: [PinType.INOUT] }, 
            { pin:74, pinType: [PinType.INOUT] },
            { pin:75, pinType: [PinType.INOUT] },
            { pin:76, pinType: [PinType.INOUT] },
            { pin:77, pinType: [PinType.INOUT] },
            { pin:78, pinType: [PinType.VCC] },
            { pin:79, pinType: [PinType.INOUT] },
            { pin:80, pinType: [PinType.INOUT] },
            { pin:81, pinType: [PinType.INOUT, PinType.CLK] },
            { pin:82, pinType: [PinType.GND] },
            { pin:83, pinType: [PinType.IN, PinType.CLK] },
            { pin:84, pinType: [PinType.IN, PinType.CLR] }       
        ] as Pin[]
    },
    {
        name: 'f1504',
        deviceType: DevicePackageType.tqfp,
        pinCount: 100,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.NC] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:5, pinType: [PinType.NC] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.NC] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.GND] },
            { pin:12, pinType: [PinType.INOUT, PinType.PD] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.VCC] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.NC] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.NC] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.GND] },
            { pin:27, pinType: [PinType.NC] },
            { pin:28, pinType: [PinType.NC] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.VCC] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.GND] },
            { pin:39, pinType: [PinType.VCC] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT] },
            { pin:42, pinType: [PinType.INOUT, PinType.PD] },
            { pin:43, pinType: [PinType.GND] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.INOUT] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.INOUT] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.NC] },
            { pin:50, pinType: [PinType.NC] },
            { pin:51, pinType: [PinType.VCC] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.NC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.NC] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.GND] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.INOUT] },
            { pin:62, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.VCC] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.INOUT] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.NC] },
            { pin:71, pinType: [PinType.INOUT] },
            { pin:72, pinType: [PinType.NC] },
            { pin:73, pinType: [PinType.INOUT, PinType.TDO] }, 
            { pin:74, pinType: [PinType.GND] },
            { pin:75, pinType: [PinType.INOUT] },
            { pin:76, pinType: [PinType.INOUT] },
            { pin:77, pinType: [PinType.NC] },
            { pin:78, pinType: [PinType.NC] },
            { pin:79, pinType: [PinType.INOUT] },
            { pin:80, pinType: [PinType.INOUT] },
            { pin:81, pinType: [PinType.INOUT] },
            { pin:82, pinType: [PinType.VCC] },
            { pin:83, pinType: [PinType.INOUT] },
            { pin:84, pinType: [PinType.INOUT] },   
            { pin:85, pinType: [PinType.INOUT, PinType.CLK] },  
            { pin:86, pinType: [PinType.GND] },  
            { pin:87, pinType: [PinType.IN, PinType.CLK] },  
            { pin:88, pinType: [PinType.IN, PinType.OE] },  
            { pin:89, pinType: [PinType.IN, PinType.CLR] },  
            { pin:90, pinType: [PinType.IN, PinType.CLR, PinType.OE] },  
            { pin:91, pinType: [PinType.VCC] },  
            { pin:92, pinType: [PinType.INOUT] },  
            { pin:93, pinType: [PinType.INOUT] },  
            { pin:94, pinType: [PinType.INOUT] },  
            { pin:95, pinType: [PinType.GND] },  
            { pin:96, pinType: [PinType.INOUT] },  
            { pin:97, pinType: [PinType.INOUT] },  
            { pin:98, pinType: [PinType.INOUT] },  
            { pin:99, pinType: [PinType.INOUT] },  
            { pin:100, pinType: [PinType.INOUT] }     
        ] as Pin[]
    },
    {
        name: 'f1504',
        deviceType: DevicePackageType.pqfp,
        pinCount: 100,
        pins:[
            { pin:1, pinType: [PinType.NC] },
            { pin:2, pinType: [PinType.NC] },
            { pin:3, pinType: [PinType.INOUT] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.VCC] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.NC] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.NC] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.GND] },
            { pin:14, pinType: [PinType.INOUT, PinType.PD] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.VCC] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.NC] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.NC] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.GND] },
            { pin:29, pinType: [PinType.NC] },
            { pin:30, pinType: [PinType.NC] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.VCC] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.GND] },
            { pin:41, pinType: [PinType.VCC] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.INOUT] },
            { pin:44, pinType: [PinType.INOUT, PinType.PD] },
            { pin:45, pinType: [PinType.GND] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.INOUT] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT] },
            { pin:51, pinType: [PinType.NC] },
            { pin:52, pinType: [PinType.NC] },
            { pin:53, pinType: [PinType.VCC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.NC] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.NC] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.INOUT] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.GND] },
            { pin:62, pinType: [PinType.INOUT] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.INOUT] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.VCC] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.INOUT] },
            { pin:71, pinType: [PinType.INOUT] },
            { pin:72, pinType: [PinType.NC] },
            { pin:73, pinType: [PinType.INOUT] }, 
            { pin:74, pinType: [PinType.NC] },
            { pin:75, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:76, pinType: [PinType.GND] },
            { pin:77, pinType: [PinType.INOUT] },
            { pin:78, pinType: [PinType.INOUT] },
            { pin:79, pinType: [PinType.NC] },
            { pin:80, pinType: [PinType.NC] },
            { pin:81, pinType: [PinType.INOUT] },
            { pin:82, pinType: [PinType.INOUT] },
            { pin:83, pinType: [PinType.INOUT] },
            { pin:84, pinType: [PinType.VCC] },   
            { pin:85, pinType: [PinType.INOUT] },  
            { pin:86, pinType: [PinType.INOUT] },  
            { pin:87, pinType: [PinType.INOUT, PinType.CLK] },  
            { pin:88, pinType: [PinType.GND] },
            { pin:89, pinType: [PinType.IN, PinType.CLK] }, 
            { pin:90, pinType: [PinType.IN, PinType.OE] },  
            { pin:91, pinType: [PinType.IN, PinType.CLR] },  
            { pin:92, pinType: [PinType.IN, PinType.CLR, PinType.OE] },  
            { pin:93, pinType: [PinType.VCC] },  
            { pin:94, pinType: [PinType.INOUT] },  
            { pin:95, pinType: [PinType.INOUT] },  
            { pin:96, pinType: [PinType.INOUT] },  
            { pin:97, pinType: [PinType.GND] },  
            { pin:98, pinType: [PinType.INOUT] },  
            { pin:99, pinType: [PinType.INOUT] },  
            { pin:100, pinType: [PinType.INOUT] }
        ] as Pin[]
    },
    
    {
        name: 'f1508',
        deviceType: DevicePackageType.tqfp,
        pinCount: 100,
        pins:[
            { pin:1, pinType: [PinType.IN, PinType.PD] },
            { pin:2, pinType: [PinType.INOUT] },
            { pin:3, pinType: [PinType.VCC] },
            { pin:4, pinType: [PinType.IN, PinType.PD] },
            { pin:5, pinType: [PinType.INOUT] },
            { pin:6, pinType: [PinType.INOUT] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.GND] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.INOUT] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT] },
            { pin:18, pinType: [PinType.VCC] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.INOUT] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.GND] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.INOUT] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.VCC] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.INOUT] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.GND] },
            { pin:39, pinType: [PinType.VCC] },
            { pin:40, pinType: [PinType.INOUT] },
            { pin:41, pinType: [PinType.INOUT, PinType.PD] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.GND] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.INOUT] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.INOUT] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT] },
            { pin:51, pinType: [PinType.VCC] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.INOUT] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.INOUT] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.GND] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.INOUT] },
            { pin:62, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.VCC] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.INOUT] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.INOUT] },
            { pin:71, pinType: [PinType.INOUT] },
            { pin:72, pinType: [PinType.INOUT] },
            { pin:73, pinType: [PinType.INOUT, PinType.TDO] }, 
            { pin:74, pinType: [PinType.GND] },
            { pin:75, pinType: [PinType.INOUT] },
            { pin:76, pinType: [PinType.INOUT] },
            { pin:77, pinType: [PinType.INOUT] },
            { pin:78, pinType: [PinType.INOUT] },
            { pin:79, pinType: [PinType.INOUT] },
            { pin:80, pinType: [PinType.INOUT] },
            { pin:81, pinType: [PinType.INOUT] },
            { pin:82, pinType: [PinType.VCC] },
            { pin:83, pinType: [PinType.INOUT] },
            { pin:84, pinType: [PinType.INOUT] },   
            { pin:85, pinType: [PinType.INOUT, PinType.CLK] },  
            { pin:86, pinType: [PinType.GND] },  
            { pin:87, pinType: [PinType.IN, PinType.CLK] },  
            { pin:88, pinType: [PinType.IN, PinType.OE] },  
            { pin:89, pinType: [PinType.IN, PinType.CLR] },  
            { pin:90, pinType: [PinType.IN, PinType.CLR, PinType.OE] },  
            { pin:91, pinType: [PinType.VCC] },  
            { pin:92, pinType: [PinType.INOUT] },  
            { pin:93, pinType: [PinType.INOUT] },  
            { pin:94, pinType: [PinType.INOUT] },  
            { pin:95, pinType: [PinType.GND] },  
            { pin:96, pinType: [PinType.INOUT] },  
            { pin:97, pinType: [PinType.INOUT] },  
            { pin:98, pinType: [PinType.INOUT] },  
            { pin:99, pinType: [PinType.INOUT] },  
            { pin:100, pinType: [PinType.INOUT] },      
        ] as Pin[]
    },
    {
        name: 'f1508',
        deviceType: DevicePackageType.pqfp,
        pinCount: 100,
        pins:[
            { pin:1, pinType: [PinType.INOUT] },
            { pin:2, pinType: [PinType.INOUT] },
            { pin:3, pinType: [PinType.INOUT, PinType.PD] },
            { pin:4, pinType: [PinType.INOUT] },
            { pin:5, pinType: [PinType.VCC] },
            { pin:6, pinType: [PinType.INOUT, PinType.TDI] },
            { pin:7, pinType: [PinType.INOUT] },
            { pin:8, pinType: [PinType.INOUT] },
            { pin:9, pinType: [PinType.INOUT] },
            { pin:10, pinType: [PinType.INOUT] },
            { pin:11, pinType: [PinType.INOUT] },
            { pin:12, pinType: [PinType.INOUT] },
            { pin:13, pinType: [PinType.GND] },
            { pin:14, pinType: [PinType.INOUT] },
            { pin:15, pinType: [PinType.INOUT] },
            { pin:16, pinType: [PinType.INOUT] },
            { pin:17, pinType: [PinType.INOUT, PinType.TMS] },
            { pin:18, pinType: [PinType.INOUT] },
            { pin:19, pinType: [PinType.INOUT] },
            { pin:20, pinType: [PinType.VCC] },
            { pin:21, pinType: [PinType.INOUT] },
            { pin:22, pinType: [PinType.INOUT] },
            { pin:23, pinType: [PinType.INOUT] },
            { pin:24, pinType: [PinType.INOUT] },
            { pin:25, pinType: [PinType.INOUT] },
            { pin:26, pinType: [PinType.INOUT] },
            { pin:27, pinType: [PinType.INOUT] },
            { pin:28, pinType: [PinType.GND] },
            { pin:29, pinType: [PinType.INOUT] },
            { pin:30, pinType: [PinType.INOUT] },
            { pin:31, pinType: [PinType.INOUT] },
            { pin:32, pinType: [PinType.INOUT] },
            { pin:33, pinType: [PinType.INOUT] },
            { pin:34, pinType: [PinType.INOUT] },
            { pin:35, pinType: [PinType.INOUT] },
            { pin:36, pinType: [PinType.VCC] },
            { pin:37, pinType: [PinType.INOUT] },
            { pin:38, pinType: [PinType.INOUT] },
            { pin:39, pinType: [PinType.INOUT] },
            { pin:40, pinType: [PinType.GND] },
            { pin:41, pinType: [PinType.VCC] },
            { pin:42, pinType: [PinType.INOUT] },
            { pin:43, pinType: [PinType.INOUT, PinType.PD] },
            { pin:44, pinType: [PinType.INOUT] },
            { pin:45, pinType: [PinType.GND] },
            { pin:46, pinType: [PinType.INOUT] },
            { pin:47, pinType: [PinType.INOUT] },
            { pin:48, pinType: [PinType.INOUT] },
            { pin:49, pinType: [PinType.INOUT] },
            { pin:50, pinType: [PinType.INOUT] },
            { pin:51, pinType: [PinType.INOUT] },
            { pin:52, pinType: [PinType.INOUT] },
            { pin:53, pinType: [PinType.VCC] },
            { pin:54, pinType: [PinType.INOUT] },
            { pin:55, pinType: [PinType.INOUT] },
            { pin:56, pinType: [PinType.INOUT] },
            { pin:57, pinType: [PinType.INOUT] },
            { pin:58, pinType: [PinType.INOUT] },
            { pin:59, pinType: [PinType.INOUT] },
            { pin:60, pinType: [PinType.INOUT] },
            { pin:61, pinType: [PinType.GND] },
            { pin:62, pinType: [PinType.INOUT] },
            { pin:63, pinType: [PinType.INOUT] },
            { pin:64, pinType: [PinType.INOUT, PinType.TCK] },
            { pin:65, pinType: [PinType.INOUT] },
            { pin:66, pinType: [PinType.INOUT] },
            { pin:67, pinType: [PinType.INOUT] },
            { pin:68, pinType: [PinType.VCC] },
            { pin:69, pinType: [PinType.INOUT] },
            { pin:70, pinType: [PinType.INOUT] },
            { pin:71, pinType: [PinType.INOUT] },
            { pin:72, pinType: [PinType.INOUT] },
            { pin:73, pinType: [PinType.INOUT] }, 
            { pin:74, pinType: [PinType.INOUT] },
            { pin:75, pinType: [PinType.INOUT, PinType.TDO] },
            { pin:76, pinType: [PinType.GND] },
            { pin:77, pinType: [PinType.INOUT] },
            { pin:78, pinType: [PinType.INOUT] },
            { pin:79, pinType: [PinType.INOUT] },
            { pin:80, pinType: [PinType.INOUT] },
            { pin:81, pinType: [PinType.INOUT] },
            { pin:82, pinType: [PinType.INOUT] },
            { pin:83, pinType: [PinType.INOUT] },
            { pin:84, pinType: [PinType.VCC] },   
            { pin:85, pinType: [PinType.INOUT] },  
            { pin:86, pinType: [PinType.INOUT] },  
            { pin:87, pinType: [PinType.INOUT, PinType.CLK] },  
            { pin:88, pinType: [PinType.GND] },
            { pin:89, pinType: [PinType.IN, PinType.CLK] }, 
            { pin:90, pinType: [PinType.IN, PinType.OE] },  
            { pin:91, pinType: [PinType.IN, PinType.CLR] },  
            { pin:92, pinType: [PinType.IN, PinType.CLR, PinType.OE] },  
            { pin:93, pinType: [PinType.VCC] },  
            { pin:94, pinType: [PinType.INOUT] },  
            { pin:95, pinType: [PinType.INOUT] },  
            { pin:96, pinType: [PinType.INOUT] },  
            { pin:97, pinType: [PinType.GND] },  
            { pin:98, pinType: [PinType.INOUT] },  
            { pin:99, pinType: [PinType.INOUT] },  
            { pin:100, pinType: [PinType.INOUT] }
        ] as Pin[]
    }
    
    
] as PinConfiguration[];

export function getDevicePins(name: string, pinCount: number, packageType: DevicePackageType){
    let pins = {} as PinConfiguration | undefined;
    try{
        pins = pinConfigurations.find(d => d && d.name === name && d.pinCount === pinCount && d.deviceType === packageType );
    }
    catch(err: any){
        console.log(`Error searching device pinmap: ${err.message}`);
    }
    return pins;
} 